spring.application.name=AtivoeOperante
spring.datasource.url=jdbc:postgresql://localhost/ativooperante
spring.datasource.username=postgres
spring.datasource.password=1234
springdoc.swagger-ui.path=/ativooperante-doc.html


